paths:
  images: "B:/Datasets/LUS_SSL/aug_us_ssl/data/bmodes"
  masks: "B:/Datasets/LUS_SSL/aug_us_ssl/data/masks"
  splits: "B:/Datasets/LUS_SSL/aug_us_ssl/splits/aug_us_ssl_splits"
  model_weights: "results/models"

data:
  height: 128
  width: 128
  min_pixel_value: 0.0
  max_pixel_value: 255.0
  num_channels: 3
  resize: true

pretrain:
  seed: 11
  epochs: 100
  batch_size: 512
  max_lr: 0.2
  warmup_epochs: 10
  weight_decay: 0.000001
  extractor: 'mobilenetv3'
  proj_nodes: [512, 512]
  use_bias: true
  imagenet_weights: true
  labelled_only: true
  method: "simclr"
  augment_pipeline: "august"
  n_cutoff_layers: 0
  exclude_idx: -1
  hparams:
    simclr:
      tau: 0.1
    barlow_twins:
      lambda_: 0.005
    vicreg:
      lambda_: 25.0
      mu: 25.0
      nu: 1.0

train:
  seed: 11
  label: 'covid-us_label'
  linear: false
  epochs: 10
  batch_size: 256
  lr_head: 0.002
  lr_extractor: 0.0002
  weight_decay: 0.000001
  extractor: 'mobilenetv3'
  extractor_weights: 'B:/Downloads/epoch=9-step=6020.ckpt'
  augment_pipeline: "supervised"

augment:
  august: